export const groups = [
  {
    id: "caching",
    name: "Caching",
    subtitle: "Make the fast path faster",
    color: "blue",
  },
  {
    id: "scaling",
    name: "Traffic & scaling",
    subtitle: "Grow without falling over",
    color: "purple",
  },
  {
    id: "data",
    name: "Data & storage",
    subtitle: "Put data in the right place",
    color: "teal",
  },
  {
    id: "messaging",
    name: "Async & messaging",
    subtitle: "Decouple the work",
    color: "orange",
  },
  {
    id: "resilience",
    name: "Reliability",
    subtitle: "Design for things to fail",
    color: "rose",
  },
  {
    id: "security",
    name: "Security & delivery",
    subtitle: "Build trust into every request",
    color: "indigo",
  },
  {
    id: "distributed",
    name: "Distributed systems",
    subtitle: "Coordinate across boundaries",
    color: "green",
  },
] as const;
export type GroupId = (typeof groups)[number]["id"];
export type Compute = "Lambda" | "EC2" | "Managed";
export type Concept = {
  id: string;
  title: string;
  group: GroupId;
  service: string;
  compute: Compute;
  description: string;
  tradeoff: string;
  experiment: string;
  steps: string[];
  minutes: number;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
};
const rows: [
  GroupId,
  string,
  string,
  string,
  Compute,
  string,
  string,
  string,
  string,
][] = [
  [
    "caching",
    "cache-aside",
    "Cache-aside",
    "ElastiCache for Valkey",
    "Lambda",
    "Keep frequently accessed data close to your application. Fetch from the database only when the cache misses.",
    "Faster reads come with stale data and another system to operate.",
    "Increase the TTL. Watch repeated requests take the shorter path.",
    "A client requests a product|The application checks the cache|On a miss, read the database and populate the cache|Repeated reads return directly from the cache",
  ],
  [
    "caching",
    "write-through",
    "Write-through cache",
    "ElastiCache + Aurora",
    "Lambda",
    "Update the database and cache on the write path, before acknowledging the request.",
    "Writes take longer; a failed cache update needs recovery. The two stores are not one transaction.",
    "Increase write traffic and compare acknowledgment latency.",
    "A client updates a product|Commit the change to the database|Update the cache with the committed value|Acknowledge after both operations succeed",
  ],
  [
    "caching",
    "write-behind",
    "Write-behind cache",
    "ElastiCache + SQS",
    "EC2",
    "Acknowledge a buffered write and persist it asynchronously.",
    "Buffer loss can lose acknowledged writes; durable queues reduce that risk.",
    "Increase traffic until the persistence worker falls behind.",
    "Accept an update into a durable buffer|Return an early acknowledgment|A worker batches pending updates|Persist the batch and retire the messages",
  ],
  [
    "caching",
    "ttl",
    "Time-to-live",
    "ElastiCache for Valkey",
    "Lambda",
    "Expire cached entries after a bounded interval, then repopulate them on demand.",
    "Short TTLs improve freshness but cause more database reads.",
    "Lower the TTL and observe the hit ratio fall.",
    "Check the entry expiration|Return the value while it is valid|An expired entry becomes a cache miss|Refresh the value and start a new TTL",
  ],
  [
    "caching",
    "eviction",
    "Cache eviction",
    "ElastiCache for Valkey",
    "EC2",
    "Choose which entry leaves a full cache using recency or frequency.",
    "LRU favors recent reads; LFU favors frequently used keys. Neither predicts future requests.",
    "Reduce the working-set capacity and observe more misses.",
    "The cache reaches its capacity|Choose the least recently used entry|Evict it to make space|A later access to that key requires a database read",
  ],
  [
    "caching",
    "invalidation",
    "Cache invalidation",
    "DynamoDB Streams + Lambda",
    "Lambda",
    "Invalidate cached values when the source of truth changes.",
    "Stream delivery is asynchronous; a small stale-read window remains.",
    "Increase propagation delay to widen the stale-read window.",
    "Commit a change to the source of truth|A stream publishes the change|The consumer invalidates the cached key|The next reader fetches a fresh value",
  ],
  [
    "caching",
    "stampede",
    "Cache stampede",
    "ElastiCache for Valkey",
    "EC2",
    "Prevent many concurrent misses for the same key from overwhelming the database.",
    "Single-flight coordination reduces duplicate work but requires bounded lock lifetimes.",
    "Compare a synchronized expiration with coalesced requests.",
    "A popular key expires|Many requests encounter the same miss|One request refreshes while the others wait|Release the waiting requests with the refreshed value",
  ],
  [
    "caching",
    "cdn-cache",
    "CDN caching",
    "CloudFront + S3",
    "Managed",
    "Serve reusable content from an edge location close to the visitor.",
    "Cache-key mistakes can leak personalized data; include the correct varying inputs.",
    "Increase the cacheable share of requests to reduce origin traffic.",
    "A visitor reaches the nearest edge|Look up the object by cache key|Fetch a missing object from the origin|Reuse the response until its freshness lifetime ends",
  ],
  [
    "scaling",
    "load-balancing",
    "Load balancing",
    "Application Load Balancer",
    "EC2",
    "Distribute incoming requests among healthy application instances.",
    "Health checks and routing improve availability but cannot create capacity.",
    "Add replicas and watch each instance receive less work.",
    "A request reaches the load balancer|Select a healthy target|Forward the request to that instance|Return its response to the client",
  ],
  [
    "scaling",
    "horizontal-scaling",
    "Horizontal scaling",
    "EC2 Auto Scaling",
    "EC2",
    "Increase capacity by adding independent workers or application replicas.",
    "Shared state and coordination can limit otherwise linear gains.",
    "Raise traffic, then add instances until the queue clears.",
    "Traffic exceeds one instance capacity|Add identical instances|Spread incoming requests across them|Total capacity increases with the replica count",
  ],
  [
    "scaling",
    "vertical-scaling",
    "Vertical scaling",
    "EC2 instance families",
    "EC2",
    "Give one machine more CPU and memory to handle a larger workload.",
    "Larger machines have a ceiling and can require disruptive resizing.",
    "Increase capacity per instance and compare saturation.",
    "A single instance approaches saturation|Choose a larger instance size|Restart or replace the instance|More work fits on that one machine",
  ],
  [
    "scaling",
    "autoscaling",
    "Target-tracking autoscaling",
    "EC2 Auto Scaling + CloudWatch",
    "EC2",
    "Adjust replica count in response to a measured demand signal.",
    "Metrics, boot time, and cooldowns create a delay before capacity catches up.",
    "Create a traffic spike and inspect the scale-out lag.",
    "Measure utilization against a target|A sustained breach triggers scale-out|New instances boot and pass health checks|Traffic redistributes across the larger fleet",
  ],
  [
    "scaling",
    "serverless",
    "Serverless concurrency",
    "Lambda",
    "Lambda",
    "Scale independent event handlers without maintaining a server fleet.",
    "Concurrency quotas and downstream connection limits still bound throughput.",
    "Raise requests beyond the configured concurrency capacity.",
    "An event invokes a function|A warm environment handles it when available|Additional concurrent work needs more environments|Excess concurrency is throttled at the configured limit",
  ],
  [
    "scaling",
    "rate-limiting",
    "Rate limiting",
    "API Gateway + AWS WAF",
    "Lambda",
    "Bound accepted request volume to protect shared capacity.",
    "Legitimate bursts can be rejected; callers need backoff and clear limits.",
    "Push traffic above capacity and watch requests receive 429s.",
    "A request reaches the admission boundary|Check the available request budget|Admit requests while capacity remains|Reject excess requests with a retryable response",
  ],
  [
    "scaling",
    "backpressure",
    "Backpressure",
    "SQS + Lambda concurrency",
    "Lambda",
    "Slow producers or bound consumer concurrency when downstream work accumulates.",
    "Backlogs absorb bursts but increase the time users wait for completion.",
    "Reduce consumers and watch queue depth grow.",
    "The producer enqueues work|Consumers process at a bounded rate|The backlog grows when arrivals exceed service|Admission control slows new work before storage is exhausted",
  ],
  [
    "scaling",
    "connection-pooling",
    "Connection pooling",
    "RDS Proxy + Aurora",
    "Lambda",
    "Reuse a bounded set of database connections across many requests.",
    "Transactions can pin connections, reducing multiplexing benefits.",
    "Increase request traffic while keeping the pool bounded.",
    "A function requests a database connection|The proxy lends an available connection|A transaction performs its work|Return the connection for another request",
  ],
  [
    "data",
    "sharding",
    "Sharding",
    "DynamoDB partition keys",
    "Managed",
    "Split data across partitions so reads and writes can scale independently.",
    "A popular partition key creates a hot spot even when other partitions are idle.",
    "Add partitions, then compare an evenly distributed workload.",
    "Hash the entity partition key|Route the request to its partition|Read or write within that partition|Other keys can be served by different partitions",
  ],
  [
    "data",
    "replication",
    "Read replicas",
    "Aurora replicas",
    "Managed",
    "Serve reads from additional database copies while retaining a writer.",
    "Replica lag means a recent write may not appear on every reader immediately.",
    "Add readers to increase read capacity and inspect the lag.",
    "Commit a write on the primary|Replicate the change to readers|Route eligible reads to a replica|Use the primary when read-after-write freshness is required",
  ],
  [
    "data",
    "indexing",
    "Secondary indexes",
    "DynamoDB global secondary indexes",
    "Managed",
    "Create an alternate access path for queries that do not use the primary key.",
    "Indexes consume storage and write capacity; DynamoDB GSIs are eventually consistent.",
    "Compare a selective index lookup with a full scan.",
    "Write the base item|Project the configured attributes into an index|Query the index by its own partition key|Fetch the relevant result without scanning the full table",
  ],
  [
    "data",
    "transactions",
    "ACID transactions",
    "Aurora PostgreSQL",
    "Managed",
    "Commit related changes atomically while enforcing isolation and durability.",
    "Stronger isolation and contended rows increase waiting and retry rates.",
    "Increase contention and observe transaction latency rise.",
    "Begin a transaction|Update related records under the chosen isolation level|Check constraints and commit atomically|Roll back all changes if a required operation fails",
  ],
  [
    "data",
    "optimistic-locking",
    "Optimistic locking",
    "DynamoDB conditional writes",
    "Lambda",
    "Reject updates based on an old version instead of holding a lock during edits.",
    "A contended record can cause repeated conflicts and retries.",
    "Increase contention to create more version conflicts.",
    "Read the item and its version|Compute the intended update|Conditionally write only if the version still matches|On conflict, reread before retrying",
  ],
  [
    "data",
    "denormalization",
    "Denormalization",
    "DynamoDB",
    "Managed",
    "Store data in the shape that reads need to avoid expensive joins.",
    "Duplicate values need coordinated updates and consume extra storage.",
    "Compare precomputed reads with additional write amplification.",
    "Identify the important query shape|Copy needed fields into a query-friendly item|Read the result in one access|Propagate source changes to the duplicated fields",
  ],
  [
    "data",
    "object-storage",
    "Object storage",
    "S3",
    "Managed",
    "Store large immutable blobs separately from queryable application metadata.",
    "Objects are not a relational query engine; keep searchable metadata elsewhere.",
    "Increase object size and compare metadata versus blob transfer.",
    "Authorize an object operation|Upload bytes to an object key|Record the key in application metadata|Download the object directly from storage",
  ],
  [
    "data",
    "data-lifecycle",
    "Data lifecycle",
    "S3 Lifecycle + Glacier",
    "Managed",
    "Move or expire objects according to their age and access requirements.",
    "Archived data may need minutes or hours to restore and can incur retrieval charges.",
    "Increase object age to see the selected storage tier change.",
    "Write a new object to the hot tier|A lifecycle rule evaluates its age|Transition eligible data into an archive tier|Restore archived data before accessing it",
  ],
  [
    "messaging",
    "queues",
    "Message queues",
    "SQS",
    "Lambda",
    "Buffer work between producers and consumers so they can run at different rates.",
    "Standard queues can deliver a message more than once; consumers must be idempotent.",
    "Raise arrivals above worker throughput and inspect the backlog.",
    "A producer sends a message|The queue durably buffers it|A worker receives and processes it|Delete the message only after processing succeeds",
  ],
  [
    "messaging",
    "pubsub",
    "Publish / subscribe",
    "SNS + SQS",
    "Lambda",
    "Deliver one event to multiple independent subscribers.",
    "Subscribers can lag or fail independently; each needs its own failure handling.",
    "Add subscribers and observe delivery fan-out.",
    "Publish an event to the topic|The topic selects matching subscriptions|Each subscriber receives its own delivery|Subscribers process without coordinating with each other",
  ],
  [
    "messaging",
    "event-streams",
    "Event streaming",
    "Kinesis Data Streams",
    "Lambda",
    "Retain an ordered sequence within each shard for multiple consumers.",
    "Order is per shard, and slow consumers can exceed the retention window.",
    "Add shards and compare throughput with ordering scope.",
    "Choose a partition key for the event|Append the record to its shard|Consumers track their own read position|Replay retained records from a previous position",
  ],
  [
    "messaging",
    "dead-letter",
    "Dead-letter queues",
    "SQS dead-letter queue",
    "Lambda",
    "Isolate repeatedly failing messages so healthy work can continue.",
    "A DLQ needs monitoring and a deliberate redrive process.",
    "Inject failures until poison messages reach the retry limit.",
    "Receive a message|Processing fails and visibility expires|Retry up to the configured receive threshold|Move persistent failures to the dead-letter queue",
  ],
  [
    "messaging",
    "idempotency",
    "Idempotent consumers",
    "DynamoDB conditional writes + SQS",
    "Lambda",
    "Make duplicate deliveries produce the same business outcome as one delivery.",
    "The deduplication record and side effect need an atomic design or a recoverable state machine.",
    "Increase duplicate delivery and inspect unique effects.",
    "Receive an event with a stable operation ID|Conditionally claim that ID|Apply the effect with transactional or recoverable state|Return the recorded result for duplicate deliveries",
  ],
  [
    "messaging",
    "ordering",
    "Ordered delivery",
    "SQS FIFO",
    "Lambda",
    "Preserve order within a message group while processing different groups in parallel.",
    "One slow message blocks later messages in its group.",
    "Increase message groups to unlock parallel consumers.",
    "Assign a message group ID|Enqueue messages in that group in order|Process the head message successfully|Release the next message from the same group",
  ],
  [
    "messaging",
    "batching",
    "Batch processing",
    "Lambda + SQS",
    "Lambda",
    "Amortize per-invocation overhead by processing several messages together.",
    "Large batches improve efficiency but increase latency and partial-failure complexity.",
    "Increase batch size and compare invocation count.",
    "Accumulate up to the batch size or time limit|Invoke one worker for the batch|Process the records individually|Return failed item identifiers for selective retry",
  ],
  [
    "messaging",
    "event-routing",
    "Event routing",
    "EventBridge",
    "Lambda",
    "Send domain events to interested targets using declarative content filters.",
    "Schemas, retry policies, and archive retention require explicit ownership.",
    "Adjust matching traffic to see how many events reach the target.",
    "Publish a structured domain event|Rules inspect source, type, and detail fields|Matching rules deliver to their targets|Handle failed deliveries using retries and a DLQ",
  ],
  [
    "resilience",
    "circuit-breaker",
    "Circuit breakers",
    "EC2 application + CloudWatch",
    "EC2",
    "Stop calls to a failing dependency temporarily so it has time to recover.",
    "An application-level circuit must distinguish transient errors from a recovering service.",
    "Increase failures to open the circuit, then probe recovery.",
    "Count failures in a bounded window|Open the circuit above its threshold|Fail fast while the circuit is open|Allow a half-open probe before resuming normal traffic",
  ],
  [
    "resilience",
    "retries",
    "Retries with backoff",
    "Step Functions",
    "Lambda",
    "Retry transient failures with increasing delays and jitter.",
    "Unbounded retries amplify outages; only retry safe or idempotent operations.",
    "Increase failures and watch retry pressure grow.",
    "The first attempt fails transiently|Wait for a backoff interval with jitter|Retry within a bounded attempt budget|Stop after success or when the budget is exhausted",
  ],
  [
    "resilience",
    "timeouts",
    "Timeout budgets",
    "API Gateway + Lambda",
    "Lambda",
    "Bound how long a caller waits and pass a remaining budget downstream.",
    "A timeout does not prove the downstream side effect was cancelled.",
    "Lower the deadline until slower operations time out.",
    "Assign an end-to-end deadline|Pass a smaller budget to the next service|Cancel local waiting at the deadline|Reconcile uncertain side effects using an operation ID",
  ],
  [
    "resilience",
    "bulkheads",
    "Bulkhead isolation",
    "Lambda reserved concurrency",
    "Lambda",
    "Allocate separate capacity pools so one workload cannot consume everything.",
    "Reserved capacity can sit idle while another isolated workload is overloaded.",
    "Overload one pool and see the other pool retain capacity.",
    "Assign critical workloads separate capacity|A noisy workload exhausts its own allocation|Reject excess work from that pool|Other pools continue serving their own requests",
  ],
  [
    "resilience",
    "health-checks",
    "Health checks",
    "Application Load Balancer",
    "EC2",
    "Route traffic away from instances that fail meaningful readiness checks.",
    "Shallow checks miss dependency failures; deep checks can create cascading removal.",
    "Fail one replica and watch the healthy fleet take its load.",
    "Probe each target at regular intervals|Count consecutive failures|Remove an unhealthy target from routing|Restore it after enough successful checks",
  ],
  [
    "resilience",
    "multi-az",
    "Multi-AZ failover",
    "Aurora + ALB",
    "Managed",
    "Place redundant components in separate availability zones.",
    "Failover still takes time; clients must refresh connections and retry safely.",
    "Remove a zone and compare remaining serving capacity.",
    "Serve through components in multiple zones|An availability zone becomes unavailable|Promote or route to healthy capacity in another zone|Reconnect clients and restore redundancy",
  ],
  [
    "resilience",
    "disaster-recovery",
    "Disaster recovery",
    "AWS Backup + S3 replication",
    "Managed",
    "Restore service after a larger failure with explicit RPO and RTO targets.",
    "Replication is not a backup; corrupted data can also replicate. Test actual restores.",
    "Increase backup age to see the potential data-loss window.",
    "Record the last usable recovery point|A disaster makes the primary unavailable|Restore data and infrastructure from tested backups|Measure lost time and time to restore service",
  ],
  [
    "resilience",
    "observability",
    "Metrics, logs & traces",
    "CloudWatch + X-Ray",
    "Lambda",
    "Connect service-level signals with request traces to explain system behavior.",
    "High-cardinality telemetry and unlimited retention can become expensive.",
    "Increase sampling to improve trace coverage at greater volume.",
    "Attach a correlation ID to the request|Record duration and outcome metrics|Emit structured logs and sampled spans|Follow a slow request across service boundaries",
  ],
  [
    "security",
    "authentication",
    "Authentication",
    "Cognito",
    "Managed",
    "Establish who a caller is using a verified identity token.",
    "Tokens have lifetimes; sign-out alone does not invalidate every already-issued access token.",
    "Increase invalid tokens to observe authentication rejection.",
    "Redirect the user through the authorization code flow|Exchange the code using PKCE|Validate issuer, audience or client ID, signature, and expiry|Associate the request with the verified subject",
  ],
  [
    "security",
    "authorization",
    "Least-privilege authorization",
    "IAM + API Gateway",
    "Lambda",
    "Allow an authenticated principal only the resources and actions it needs.",
    "Identity alone grants no access; application-level ownership checks are still required.",
    "Try cross-user access and observe the ownership boundary.",
    "Verify the caller identity|Evaluate allowed actions and resource ownership|Deny operations outside that scope|Record the authorization outcome",
  ],
  [
    "security",
    "encryption",
    "Encryption at rest",
    "KMS + S3",
    "Managed",
    "Protect stored data using managed keys and controlled decryption permissions.",
    "Encryption does not replace access control; key loss or denial can make data inaccessible.",
    "Compare authorized and denied decrypt operations.",
    "Generate or obtain a data encryption key|Encrypt the object using that key|Protect the data key with KMS|Require authorized key access when decrypting",
  ],
  [
    "security",
    "secrets",
    "Secrets rotation",
    "Secrets Manager",
    "Lambda",
    "Retrieve credentials at runtime and replace them without embedding secrets in source.",
    "Applications need to refresh cached credentials during rotation.",
    "Increase credential-cache age to expose a rotation window.",
    "Fetch the current secret under an IAM role|Cache it for a bounded interval|Rotate and validate a new credential|Refresh clients before retiring the previous version",
  ],
  [
    "security",
    "network-isolation",
    "Network isolation",
    "VPC + security groups",
    "EC2",
    "Restrict reachable services using subnet placement and explicit traffic rules.",
    "Private subnets need deliberate egress paths for dependencies and updates.",
    "Attempt a direct database connection outside the allowed group.",
    "Accept HTTPS at the public entry point|Forward only allowed traffic to private compute|Permit database access from the application group|Deny direct access from untrusted network sources",
  ],
  [
    "security",
    "edge-protection",
    "Edge protection",
    "AWS WAF + CloudFront",
    "Managed",
    "Filter abusive HTTP traffic before it consumes origin capacity.",
    "Rules can reject legitimate traffic; monitor and tune before enforcing broadly.",
    "Raise abusive traffic and inspect the requests reaching origin.",
    "Inspect a request at the edge|Evaluate managed and custom rules|Block matching malicious patterns|Forward allowed requests to the origin",
  ],
  [
    "security",
    "blue-green",
    "Blue / green deployments",
    "CodeDeploy + ALB",
    "EC2",
    "Prepare a complete new environment and switch traffic after validation.",
    "Running two environments costs more, and schema changes must stay compatible.",
    "Shift traffic to the new fleet and test rollback.",
    "Deploy the candidate to the green environment|Validate readiness and application checks|Switch traffic from blue to green|Keep the old environment available for rollback",
  ],
  [
    "security",
    "canary",
    "Canary releases",
    "Lambda aliases + CodeDeploy",
    "Lambda",
    "Send a small share of traffic to a new version before broader rollout.",
    "Small samples can miss rare failures; use representative metrics and a sufficient observation window.",
    "Increase the canary share to reveal its effect on errors.",
    "Publish an immutable candidate version|Route a small traffic weight to it|Compare error and latency signals|Promote gradually or roll back on alarms",
  ],
  [
    "distributed",
    "eventual-consistency",
    "Eventual consistency",
    "DynamoDB global tables",
    "Managed",
    "Allow replicas to converge after updates propagate asynchronously.",
    "Different readers may see different values during the replication window.",
    "Increase propagation delay and inspect stale reads.",
    "Commit a write in the first region|A remote replica still holds the previous value|Replicate the update asynchronously|Both replicas converge when propagation completes",
  ],
  [
    "distributed",
    "strong-consistency",
    "Strongly consistent reads",
    "DynamoDB regional tables",
    "Managed",
    "Read the latest successful write from a supported table access path.",
    "Strong reads consume more capacity and are not available on global secondary indexes.",
    "Compare fresh regional reads with eventual reads.",
    "Write an item successfully|Request a strongly consistent table read|Read the latest committed value|Pay the stronger read capacity cost",
  ],
  [
    "distributed",
    "cap",
    "CAP under a partition",
    "DynamoDB global tables / quorum store",
    "EC2",
    "Explore why a partitioned system cannot promise both linearizable consistency and every-request availability.",
    "CAP applies during network partitions; it is not a general pick-two checklist.",
    "Partition replicas and compare stale availability with rejected writes.",
    "A network partition separates replicas|An available path accepts operations locally|A consistency-first quorum path rejects unsafe operations|Heal the partition and reconcile accepted updates",
  ],
  [
    "distributed",
    "cqrs",
    "CQRS",
    "DynamoDB Streams + Lambda",
    "Lambda",
    "Separate the write model from a read model optimized for queries.",
    "Projection lag makes the read model temporarily stale and adds operational work.",
    "Increase projection delay and compare the write and read models.",
    "Validate a command against the write model|Commit its change and publish a change event|Project the event into the query model|Serve queries from that read-optimized view",
  ],
  [
    "distributed",
    "event-sourcing",
    "Event sourcing",
    "DynamoDB + Streams",
    "Lambda",
    "Persist domain events as the record of change and derive current state by replay.",
    "Event schema evolution, ordering, and replay cost need careful design.",
    "Increase history length and compare replay with a snapshot.",
    "Append a versioned domain event conditionally|Retain the immutable event history|Fold events into current state|Replay from a snapshot to rebuild a projection",
  ],
  [
    "distributed",
    "sagas",
    "Distributed sagas",
    "Step Functions",
    "Lambda",
    "Coordinate several local transactions with compensating actions when a later step fails.",
    "Compensation is a new business action, not a guaranteed database rollback.",
    "Inject a failure after payment to trigger compensation.",
    "Reserve inventory|Authorize payment|Attempt fulfillment|On failure, refund payment and release the reservation",
  ],
  [
    "distributed",
    "distributed-locks",
    "Distributed leases",
    "DynamoDB conditional writes",
    "EC2",
    "Coordinate exclusive work using expiring leases and monotonically increasing fencing tokens.",
    "Lease expiry alone is unsafe; downstream resources must reject stale fencing tokens.",
    "Pause a lease holder beyond expiry and reject its stale token.",
    "Conditionally acquire an expiring lease|Receive a new monotonic fencing token|A paused worker outlives its lease|Reject writes carrying its stale token",
  ],
  [
    "distributed",
    "consistent-hashing",
    "Consistent hashing",
    "EC2 application ring",
    "EC2",
    "Assign keys to points on a ring to reduce key movement when membership changes.",
    "Skew and uneven nodes require virtual nodes or a weighted strategy.",
    "Add one node and compare remapped keys with modulo hashing.",
    "Hash each node and key onto the ring|Assign a key to the next node clockwise|Add a node with virtual positions|Move only keys in the newly owned ranges",
  ],
];
// Reviewed by mechanism complexity, rather than catalog position.
const beginner = new Set([
  "cache-aside",
  "ttl",
  "cdn-cache",
  "load-balancing",
  "horizontal-scaling",
  "vertical-scaling",
  "rate-limiting",
  "object-storage",
  "queues",
  "pubsub",
  "authentication",
  "network-isolation",
]);
const advanced = new Set([
  "stampede",
  "transactions",
  "idempotency",
  "circuit-breaker",
  "multi-az",
  "disaster-recovery",
  "cap",
  "event-sourcing",
  "sagas",
  "distributed-locks",
  "consistent-hashing",
]);
export const concepts: Concept[] = rows.map(
  ([
    group,
    id,
    title,
    service,
    compute,
    description,
    tradeoff,
    experiment,
    steps,
  ]) => ({
    group,
    id,
    title,
    service,
    compute,
    description,
    tradeoff,
    experiment,
    steps: steps.split("|"),
    minutes: advanced.has(id) ? 18 : beginner.has(id) ? 8 : 12,
    difficulty: advanced.has(id)
      ? "Advanced"
      : beginner.has(id)
        ? "Beginner"
        : "Intermediate",
  }),
);
export const defaultConcept = concepts[0];
export function getConcept(id: string) {
  return concepts.find((concept) => concept.id === id);
}
