import { concepts, getConcept } from "./catalog";

export type Family =
  | "cache"
  | "fleet"
  | "queue"
  | "replica"
  | "record"
  | "circuit"
  | "workflow"
  | "identity"
  | "network"
  | "hash";
export type Knob = {
  key: string;
  label: string;
  min: number;
  max: number;
  initial: number;
  unit: string;
};
export type Lesson = {
  id: string;
  family: Family;
  controls: Knob[];
  contrast: Record<string, number>;
  contrastName: string;
  problem: string;
  analogy: string;
  misconception: string;
  code: string;
  prerequisites: string[];
  challenge: {
    question: string;
    options: [string, string];
    answer: number;
    explanation: string;
  };
  reference: string;
  fault?: string;
  assumptions: string;
};
const k = (
  key: string,
  label: string,
  min: number,
  max: number,
  initial: number,
  unit = "",
): Knob => ({ key, label, min, max, initial, unit });
const ttl = () => k("ttl", "Entry lifetime", 1, 20, 8, "s");
const lag = () => k("lag", "Propagation delay", 0, 10, 3, "s");
const workers = () => k("workers", "Workers", 1, 4, 2);
const arrivals = () => k("arrivals", "Messages arriving", 1, 5, 2, "/s");
const replicas = () => k("replicas", "Instances", 1, 5, 3);
const rate = () => k("rate", "Requests arriving", 1, 10, 6, "/s");
const doc = (path: string) => `https://docs.aws.amazon.com/${path}`;
const cacheDoc = doc(
  "whitepapers/latest/database-caching-strategies-using-redis/caching-patterns.html",
);
const queueDoc = doc(
  "AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html",
);
const dynamoDoc = doc("amazondynamodb/latest/developerguide/HowItWorks.html");
const lesson = (
  id: string,
  family: Family,
  controls: Knob[],
  contrast: Record<string, number>,
  contrastName: string,
  problem: string,
  analogy: string,
  misconception: string,
  code: string,
  prerequisites: string[],
  question: string,
  options: [string, string],
  answer: number,
  explanation: string,
  reference: string,
  fault?: string,
  assumptions = "A finite workload in simulated seconds. Values illustrate the mechanism, not AWS service performance.",
): Lesson => ({
  id,
  family,
  controls,
  contrast,
  contrastName,
  problem,
  analogy,
  misconception,
  code,
  prerequisites,
  challenge: { question, options, answer, explanation },
  reference,
  fault,
  assumptions,
});

export const lessons: Lesson[] = [
  lesson(
    "cache-aside",
    "cache",
    [ttl(), k("capacity", "Cache slots", 1, 6, 4, "keys")],
    { ttl: 2 },
    "Short-lived entries",
    "Repeated product reads keep reaching the database.",
    "Keep the books you use on your desk; the library is still the source of truth.",
    "A cache hit can be stale; the database does not automatically update this copy.",
    "value = cache.get(key)\nif value is missing or expired:\n  value = database.read(key)\n  cache.put(key, value, ttl)\nreturn value",
    [],
    "What does a shorter TTL usually increase?",
    ["Database reads", "Cache capacity"],
    0,
    "Expired entries must be fetched again, even when the underlying value has not changed.",
    cacheDoc,
    "Origin unavailable",
  ),
  lesson(
    "write-through",
    "cache",
    [ttl(), k("writes", "Write every", 2, 8, 4, "requests")],
    { writes: 2 },
    "Write-heavy workload",
    "Readers should see an updated value immediately after a successful write.",
    "Update the master address book, then the desk copy, before saying done.",
    "Two successful writes are not one atomic transaction.",
    "database.commit(key, value)\ntry: cache.put(key, value, ttl)\ncatch: invalidate_and_report_partial_write()\nacknowledge()",
    ["cache-aside"],
    "If the database commits but the cache write fails, what is true?",
    ["Neither write happened", "The database commit still exists"],
    1,
    "The caller needs recovery because the two systems do not share a transaction.",
    cacheDoc,
    "Cache write unavailable",
  ),
  lesson(
    "write-behind",
    "queue",
    [arrivals(), workers()],
    { arrivals: 5, workers: 1 },
    "Persistence falls behind",
    "Fast acknowledgments hide a slow persistence path.",
    "Take a numbered order slip now; the kitchen prepares it later.",
    "Accepted work is not yet durable in the final database. This example buffers durably first.",
    "queue.send(update)\nreturn accepted\nworker: persist(update); queue.delete(update)",
    ["queues"],
    "When the buffer accepts an update, has the database necessarily committed it?",
    [
      "No, the worker may still be waiting",
      "Yes, acknowledgment proves completion",
    ],
    0,
    "Acknowledgment reports durable buffer acceptance; completion occurs in a later event.",
    queueDoc,
    "Persistence workers stopped",
  ),
  lesson(
    "ttl",
    "cache",
    [ttl()],
    { ttl: 2 },
    "Frequent expiration",
    "An old cached price must not live forever.",
    "A library card expires at a known time, even if nobody checks it.",
    "Expiration bounds reuse, not the freshness of the original read.",
    "if clock >= entry.expiresAt:\n  cache.delete(key)\n  entry = fetch_and_cache(key)",
    ["cache-aside"],
    "At exactly expiresAt, may this model reuse the entry?",
    ["Yes", "No"],
    1,
    "The validity rule is clock < expiresAt. The boundary is a miss.",
    cacheDoc,
    "Origin unavailable",
  ),
  lesson(
    "eviction",
    "cache",
    [
      k("capacity", "Cache slots", 1, 6, 3, "keys"),
      k("policy", "Policy: 0 LRU · 1 LFU", 0, 1, 0),
    ],
    { capacity: 1 },
    "One cache slot",
    "A six-key working set competes for limited memory.",
    "A small desk forces you to put one book away when another arrives.",
    "LRU and LFU cannot predict the next request.",
    "if cache.full():\n  victim = least_recent() if LRU else least_frequent()\n  cache.remove(victim)\ncache.put(key, value)",
    ["cache-aside"],
    "Which field does LRU use to choose a victim?",
    ["Last access time", "Largest value"],
    0,
    "Least recently used removes the entry with the oldest access, not the biggest value.",
    cacheDoc,
    "Origin unavailable",
  ),
  lesson(
    "invalidation",
    "cache",
    [lag(), ttl()],
    { lag: 8 },
    "Slow invalidation",
    "A product changes while cached copies still hold the previous version.",
    "Recall an outdated notice from every noticeboard.",
    "Asynchronous invalidation leaves a real stale-read window.",
    "database.commit(newVersion)\nstream.onChange(key): cache.delete(key)\nnextRead: fetch_current_version()",
    ["cache-aside", "eventual-consistency"],
    "Can a read before invalidation arrives return the old value?",
    ["Yes", "No"],
    0,
    "The cache cannot know about the source update before the change event arrives.",
    doc("amazondynamodb/latest/developerguide/Streams.html"),
    "Invalidation consumer stopped",
  ),
  lesson(
    "stampede",
    "cache",
    [
      k("burst", "Readers at expiry", 2, 10, 6),
      k("coalesce", "Single-flight: 0 off · 1 on", 0, 1, 1),
      ttl(),
    ],
    { coalesce: 0 },
    "Uncoordinated readers",
    "Many readers miss the same expired key together.",
    "One person fetches the shared book while everyone else waits.",
    "A lock needs an expiry and failure recovery; it is not a permanent ownership claim.",
    "if miss:\n  with bounded_single_flight(key):\n    recheck_cache()\n    fetch_once_and_release_waiters()",
    ["cache-aside", "distributed-locks"],
    "With six concurrent misses and coalescing, how many origin reads refresh the key?",
    ["Six", "One"],
    1,
    "One leader refreshes and shares its result. The burst has one key.",
    cacheDoc,
    "Origin unavailable",
  ),
  lesson(
    "cdn-cache",
    "cache",
    [ttl(), k("cacheable", "Public requests", 0, 100, 80, "%")],
    { cacheable: 20 },
    "Mostly private requests",
    "Far-away visitors repeatedly fetch the same public assets.",
    "Keep copies at neighborhood branches, closer to readers.",
    "Personalized responses must not share an unsafe public cache key.",
    "if request.isPublic:\n  return edge.getOrFetch(cacheKey, origin, ttl)\nreturn origin.fetch(privateRequest)",
    ["cache-aside"],
    "Should this example cache private requests in the shared edge cache?",
    ["Yes", "No"],
    1,
    "Private requests bypass the public cache to avoid mixing users’ data.",
    doc("AmazonCloudFront/latest/DeveloperGuide/Introduction.html"),
    "Origin unavailable",
  ),

  lesson(
    "load-balancing",
    "fleet",
    [rate(), replicas()],
    { replicas: 1 },
    "One serving instance",
    "One application instance is saturated while another has room.",
    "A host seats guests at the next available table.",
    "Routing spreads capacity; it does not manufacture capacity.",
    "healthy = targets.filter(readiness_passed)\ntarget = round_robin(healthy)\nforward_if_target_has_capacity(request)",
    [],
    "Does a load balancer alone increase the capacity of its targets?",
    ["Yes", "No"],
    1,
    "Additional healthy instances provide capacity; the balancer distributes the work.",
    doc("elasticloadbalancing/latest/application/introduction.html"),
    "First instance fails",
  ),
  lesson(
    "horizontal-scaling",
    "fleet",
    [rate(), replicas()],
    { replicas: 5 },
    "Add independent instances",
    "Traffic exceeds the work one instance can finish.",
    "Open more checkout lanes for independent customers.",
    "Shared database contention can stop linear scaling.",
    "while demand > ready_capacity:\n  add_stateless_instance()\nroute_to_ready_instances()",
    ["load-balancing"],
    "Which assumption makes the modeled gain close to linear?",
    ["Requests are independent", "Every request locks the same row"],
    0,
    "Independent work can spread across ready instances without a shared bottleneck.",
    doc("autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html"),
    "First instance fails",
  ),
  lesson(
    "vertical-scaling",
    "fleet",
    [rate(), k("capacity", "Single-instance capacity", 1, 10, 3, "req/s")],
    { capacity: 8 },
    "Larger instance",
    "One process needs more resources without being distributed.",
    "Replace one small delivery van with a larger van.",
    "A bigger machine still has a ceiling and a single failure domain.",
    "stop_or_replace_instance()\ninstance = provision_larger_shape()\nresume_after_readiness()",
    [],
    "After increasing this one machine’s capacity, how many independent machines exist?",
    ["Several", "One"],
    1,
    "Vertical scaling changes capacity on the same logical instance.",
    doc("AWSEC2/latest/UserGuide/instance-types.html"),
    "Instance fails",
  ),
  lesson(
    "autoscaling",
    "fleet",
    [
      rate(),
      k("replicas", "Maximum instances", 2, 5, 4),
      k("delay", "Instance boot delay", 1, 10, 4, "s"),
    ],
    { delay: 9 },
    "Slow scale-out",
    "Demand rises before new capacity is ready.",
    "Calling more staff does not teleport them to the store.",
    "A scaling decision is not an immediately healthy instance.",
    "if utilization > target:\n  launch_instance()\nawait boot_and_readiness()\nadd_to_serving_pool()",
    ["horizontal-scaling"],
    "During boot delay, does the new instance serve requests?",
    ["No", "Yes"],
    0,
    "It contributes capacity only after its ready event.",
    doc("autoscaling/ec2/userguide/as-scaling-target-tracking.html"),
    "First instance fails",
  ),
  lesson(
    "serverless",
    "fleet",
    [rate(), k("concurrency", "Concurrent handlers", 1, 10, 4)],
    { concurrency: 2 },
    "Low concurrency limit",
    "Concurrent work reaches a bounded execution limit.",
    "A venue can open many booths, but permits still limit occupancy.",
    "Serverless does not mean unlimited downstream capacity.",
    "if active >= concurrency_limit: throttle()\nelse: invoke_handler(); release_on_finish()",
    [],
    "What happens when all allowed handlers are busy?",
    ["A quota disappears", "Excess requests are throttled"],
    1,
    "This model treats each invocation as one second of work and enforces its concurrency limit.",
    doc("lambda/latest/dg/lambda-concurrency.html"),
    "Handler unavailable",
  ),
  lesson(
    "rate-limiting",
    "fleet",
    [
      rate(),
      k("tokens", "Token refill rate", 1, 10, 4, "tokens/s"),
      k("burst", "Bucket size", 1, 12, 6, "tokens"),
    ],
    { tokens: 2, burst: 2 },
    "Tighter admission budget",
    "Bursts can overwhelm a shared dependency.",
    "Only people holding a ticket may enter the venue.",
    "A rejected request was not accepted and later lost.",
    "tokens = min(bucket, tokens + refill)\nif tokens >= 1: tokens -= 1; admit()\nelse: reject(429)",
    [],
    "How is a request with no remaining token classified?",
    ["Rejected before service", "Completed successfully"],
    0,
    "The admission boundary returns a rejection without doing downstream work.",
    doc("apigateway/latest/developerguide/http-api-throttling.html"),
  ),
  lesson(
    "backpressure",
    "queue",
    [arrivals(), workers(), k("limit", "Buffer limit", 2, 20, 8, "messages")],
    { arrivals: 5, workers: 1, limit: 4 },
    "Bounded overload",
    "The producer can create work faster than workers can finish it.",
    "Stop taking kitchen orders when the order rail is full.",
    "Unbounded buffering hides overload; it cannot increase service capacity.",
    "if pending >= buffer_limit: ask_producer_to_wait()\nelse: queue.send(message)\nworker: process_then_ack()",
    ["queues"],
    "If arrivals exceed worker capacity, what prevents unbounded growth here?",
    ["The buffer limit rejects new work", "The queue makes workers faster"],
    0,
    "Admission slows the producer when the bounded pending buffer is full.",
    queueDoc,
    "Workers stopped",
  ),
  lesson(
    "connection-pooling",
    "fleet",
    [rate(), k("pool", "Available connections", 1, 10, 3)],
    { pool: 1 },
    "Small connection pool",
    "Many short requests compete for a small database connection budget.",
    "Borrow and return a shared set of tools.",
    "A pinned transaction cannot lend its connection to another request.",
    "connection = pool.try_acquire()\nif absent: wait_with_deadline()\ntry: query(connection)\nfinally: pool.release(connection)",
    ["transactions"],
    "When is a borrowed connection reusable?",
    ["After the transaction releases it", "While still pinned"],
    0,
    "A connection occupied by a transaction remains unavailable to other callers.",
    doc("AmazonRDS/latest/AuroraUserGuide/rds-proxy.html"),
    "Database unavailable",
  ),

  lesson(
    "sharding",
    "hash",
    [
      k("nodes", "Partitions", 2, 6, 3),
      k("skew", "Hot-key requests", 0, 100, 20, "%"),
    ],
    { skew: 90 },
    "Hot partition",
    "A large data set needs more than one partition.",
    "Sort mail into independent delivery districts.",
    "More partitions do not split one hot key automatically.",
    "partition = hash(partition_key) % count\nread_or_write(partition, key)\nmonitor_load_per_partition()",
    [],
    "Will adding partitions spread requests for the same hot key?",
    ["No", "Yes"],
    0,
    "Every request for that key still uses the same partition unless the key design changes.",
    doc("amazondynamodb/latest/developerguide/bp-partition-key-design.html"),
  ),
  lesson(
    "replication",
    "replica",
    [lag(), k("readers", "Read replicas", 1, 4, 2)],
    { lag: 8 },
    "Lagging readers",
    "Reads need more serving copies without adding writers.",
    "Copy a master document to several reading desks.",
    "A read replica need not reflect the latest acknowledged write.",
    "primary.commit(value, version)\nreplicate_in_order(to_readers)\nread_from_replica_unless_freshness_required()",
    [],
    "Can a reader lag behind the writer?",
    ["No", "Yes"],
    1,
    "Asynchronous replication takes simulated time before each copy advances.",
    doc("AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html"),
    "Replication link disconnected",
  ),
  lesson(
    "indexing",
    "record",
    [
      k("selectivity", "Matching rows", 1, 20, 3),
      k("indexed", "Use index: 0 no · 1 yes", 0, 1, 1),
    ],
    { indexed: 0 },
    "Full table scan",
    "A query by category should not scan every product.",
    "Use the book’s index instead of reading every page.",
    "An index adds writes and storage; it is not a free copy.",
    "base.put(item)\nindex.project(item.category, item.id)\nquery: index.lookup(category) or scan(base)",
    [],
    "With a selective index, which work decreases?",
    ["Rows examined for the query", "Number of source writes"],
    0,
    "The alternate access path finds matching rows directly; writes still maintain it.",
    doc("amazondynamodb/latest/developerguide/GSI.html"),
  ),
  lesson(
    "transactions",
    "record",
    [
      k("conflict", "Contending clients", 0, 5, 1),
      k("fail", "Reject transfer: 0 no · 1 yes", 0, 1, 0),
    ],
    { fail: 1 },
    "Constraint failure",
    "Moving money must debit and credit together.",
    "Two ledger entries must be sealed in the same envelope.",
    "Intermediate writes must not leak out as a committed partial transfer.",
    "begin()\ndebit(A, 10); credit(B, 10)\nif constraints_pass: commit()\nelse: rollback()",
    [],
    "After rollback, what is the sum of the two balances?",
    ["Unchanged", "Reduced by the debit"],
    0,
    "The model commits both changes or neither, preserving the total.",
    "https://www.postgresql.org/docs/current/tutorial-transactions.html",
    "Transaction dependency fails",
  ),
  lesson(
    "optimistic-locking",
    "record",
    [k("conflict", "Concurrent stale editors", 0, 5, 2)],
    { conflict: 5 },
    "Contended updates",
    "Two users edit the same version without holding a long lock.",
    "Accept a correction only if its page revision is still current.",
    "Blindly retrying the same old version cannot fix a conflict.",
    "old = read(item)\nwrite(new_value, condition = version == old.version)\non_conflict: reread_and_recompute()",
    ["transactions"],
    "After a version conflict, what should a client do?",
    ["Retry the old value forever", "Reread and recompute"],
    1,
    "The condition prevents overwriting an intervening committed update.",
    doc(
      "amazondynamodb/latest/developerguide/BestPractices_ImplementingVersionControl.html",
    ),
  ),
  lesson(
    "denormalization",
    "replica",
    [lag(), k("copies", "Duplicated read views", 1, 4, 2)],
    { copies: 4, lag: 6 },
    "More duplicated views",
    "A common read joins data from several places.",
    "Write the delivery address on each order slip for quick access.",
    "Copied values must be maintained after the original changes.",
    "source.update(address)\nfor view in dependent_views:\n  enqueue_projection(view, address)\nread(prejoined_view)",
    ["replication"],
    "What grows when more read views contain the same field?",
    ["Update work", "The number of authoritative originals"],
    0,
    "One source update fans out into multiple view writes.",
    dynamoDoc,
    "Projection consumer stopped",
  ),
  lesson(
    "object-storage",
    "record",
    [
      k("size", "Object size", 1, 20, 8, "MB"),
      k("bandwidth", "Transfer rate", 1, 10, 4, "MB/s"),
    ],
    { size: 20, bandwidth: 2 },
    "Large blob transfer",
    "Images should not travel through every database query.",
    "Store a parcel in a warehouse and keep its tracking number in a ledger.",
    "An object key is not proof that an upload has completed.",
    "upload_object(bytes)\nawait_upload_success()\nmetadata.save(object_key, checksum)\ndownload_directly_with_authorized_url()",
    [],
    "When should metadata mark the object ready?",
    ["After the complete upload", "After the first byte"],
    0,
    "The modeled metadata pointer becomes ready only after all bytes arrive.",
    doc("AmazonS3/latest/userguide/Welcome.html"),
    "Object transfer disconnected",
  ),
  lesson(
    "data-lifecycle",
    "record",
    [
      k("age", "Initial object age", 0, 100, 20, "days"),
      k("restore", "Archive restore duration", 1, 8, 3, "s"),
    ],
    { age: 95 },
    "Archived object",
    "Old objects cost money even when rarely read.",
    "Move old files from your desk to a remote archive.",
    "An archived object may require a restore before access.",
    "if age >= 90: tier = ARCHIVE\nelse if age >= 30: tier = INFREQUENT\nif archived_read: restore_then_download()",
    ["object-storage"],
    "Can this modeled archived object be read before restore completes?",
    ["Yes", "No"],
    1,
    "Restoration introduces a waiting state. Simulated seconds stand for an illustrative restore interval.",
    doc("AmazonS3/latest/userguide/object-lifecycle-mgmt.html"),
  ),

  lesson(
    "queues",
    "queue",
    [arrivals(), workers()],
    { arrivals: 5, workers: 1 },
    "Producer outruns workers",
    "An order request should not wait for a slow background task.",
    "A durable to-do tray separates accepting a job from finishing it.",
    "Deleting a message before the side effect can lose work.",
    "send(message)\nreceive_with_visibility_timeout()\nprocess(message)\ndelete_only_after_success()",
    [],
    "Does accepting five messages with one busy worker mean five completions?",
    ["No", "Yes"],
    0,
    "The queue can accept work faster than a worker completes it; the remainder stays pending.",
    queueDoc,
    "Workers stopped",
  ),
  lesson(
    "pubsub",
    "queue",
    [
      k("subscribers", "Independent subscribers", 1, 4, 2),
      k("slow", "Slow subscriber delay", 1, 6, 2, "s"),
    ],
    { subscribers: 4, slow: 6 },
    "Slow independent subscriber",
    "One order event must trigger billing, analytics, and email.",
    "A newsletter gives every subscriber their own copy.",
    "A shared work queue delivers to competing consumers, not every subscriber.",
    "for subscription in matching_subscriptions:\n  subscription.queue.send(copy(event))\neach_subscriber_acknowledges_independently()",
    ["queues"],
    "If email is slow, must analytics stop processing its copy?",
    ["No", "Yes"],
    0,
    "Separate subscriber queues isolate backlog and progress.",
    doc("sns/latest/dg/sns-sqs-as-subscriber.html"),
    "First subscriber stopped",
  ),
  lesson(
    "event-streams",
    "queue",
    [
      k("shards", "Ordered shards", 1, 4, 2),
      k("slow", "Consumer poll interval", 1, 5, 2, "s"),
    ],
    { slow: 5 },
    "Slow stream reader",
    "Consumers need to revisit a retained ordered history.",
    "Read a journal with your own bookmark; do not tear out read pages.",
    "Ordering is within a shard, not automatically across all shards.",
    "append(shard_for(key), event)\nrecords = read_after(checkpoint[shard])\nprocess(records); advance_checkpoint()",
    ["queues"],
    "After a consumer reads a retained event, is the event deleted?",
    ["Yes", "No"],
    1,
    "Stream records remain in this finite retention window so another consumer can replay them.",
    doc("streams/latest/dev/key-concepts.html"),
    "Consumer stopped",
  ),
  lesson(
    "dead-letter",
    "queue",
    [arrivals(), workers(), k("attempts", "Maximum receives", 1, 5, 3)],
    { attempts: 1 },
    "Short retry budget",
    "One poison message keeps consuming worker time.",
    "Move an unreadable order slip aside so the kitchen can continue.",
    "A DLQ isolates work; it does not repair the payload.",
    "try: process(message); delete(message)\ncatch:\n  if receives >= max_receives: move_to_dlq()\n  else: await_visibility_timeout()",
    ["queues", "retries"],
    "What must happen before safely redriving poison work?",
    ["Repair the cause", "Only increase worker count"],
    0,
    "Redrive without fixing the poison payload repeats the same failure. Recovery here repairs it before redrive.",
    doc(
      "AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html",
    ),
    "Poison payload enabled",
  ),
  lesson(
    "idempotency",
    "queue",
    [
      k("duplicates", "Duplicate deliveries", 0, 4, 2),
      workers(),
      k("enabled", "Deduplicate: 0 off · 1 on", 0, 1, 1),
    ],
    { enabled: 0 },
    "Unsafe duplicate effects",
    "A retried order event must not charge the customer twice.",
    "Stamp a ticket when used and recognize the same ticket on return.",
    "Claiming an ID separately from a side effect is not atomic by itself.",
    "transaction:\n  if result_exists(operation_id): return result\n  apply_effect(); record_result(operation_id)\nacknowledge_delivery()",
    ["queues", "transactions"],
    "Four deliveries share an operation ID. How many business effects should commit?",
    ["One", "Four"],
    0,
    "This model explicitly makes the effect and deduplication result one atomic transaction.",
    dynamoDoc,
    "Workers stopped",
  ),
  lesson(
    "ordering",
    "queue",
    [arrivals(), workers(), k("groups", "Message groups", 1, 4, 2)],
    { groups: 1 },
    "One ordered group",
    "Orders for one customer need order; other customers should proceed.",
    "Each checkout lane serves its own line in order.",
    "FIFO group ordering does not impose one global order over all groups.",
    "for group in ready_groups:\n  process(head(group))\n  acknowledge_before_next_in_same_group()",
    ["queues"],
    "Can two different groups process concurrently?",
    ["Yes", "No"],
    0,
    "Each group has an independent head-of-line constraint.",
    doc(
      "AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-understanding-logic.html",
    ),
    "First group worker stopped",
  ),
  lesson(
    "batching",
    "queue",
    [
      arrivals(),
      k("batch", "Maximum batch size", 1, 5, 3),
      k("window", "Batch wait window", 1, 5, 2, "s"),
    ],
    { batch: 5, window: 5 },
    "Larger batches",
    "Invocation overhead dominates tiny independent messages.",
    "Carry several letters in one trip instead of one letter per trip.",
    "A failed record does not require repeating every successful record.",
    "batch = collect(max_size, max_wait)\nfailed = process_each(batch)\nack_successes_and_retry_only(failed)",
    ["queues"],
    "What is the cost of waiting for a larger batch?",
    ["Longer wait before processing", "Guaranteed duplicate effects"],
    0,
    "Batching amortizes invocations but delays messages until the size or time limit is reached.",
    doc("lambda/latest/dg/with-sqs.html"),
    "Batch worker stopped",
  ),
  lesson(
    "event-routing",
    "queue",
    [k("match", "Order-created events", 0, 100, 50, "%")],
    { match: 20 },
    "Selective route",
    "An email worker only needs order-created events.",
    "A mailroom sorts envelopes by their address.",
    "A nonmatching event is filtered, not a failed delivery.",
    'bus.publish(event)\nif event.type == "order.created":\n  target.queue.send(event)',
    ["pubsub"],
    "What happens to a nonmatching event for this rule?",
    ["The target receives it anyway", "This target gets no delivery"],
    1,
    "Only matching event types create work at this target.",
    doc("eventbridge/latest/userguide/eb-event-patterns.html"),
    "Target worker stopped",
  ),

  lesson(
    "circuit-breaker",
    "circuit",
    [
      k("threshold", "Consecutive failures to open", 1, 5, 3),
      k("cooldown", "Open-state cooldown", 1, 8, 3, "s"),
    ],
    { threshold: 1, cooldown: 6 },
    "Fast trip, slower probe",
    "Repeated calls hit a temporarily unavailable dependency.",
    "Trip an electrical breaker, then test the circuit before restoring power.",
    "Open is not permanent; half-open probes decide recovery.",
    "if OPEN and cooldown_elapsed: state = HALF_OPEN\nif OPEN: reject_locally()\ntry_one_probe_or_call()\non_success: close(); on_threshold_failure: open()",
    ["timeouts"],
    "After cooldown, what should a breaker do?",
    ["Allow a bounded probe", "Send all waiting calls at once"],
    0,
    "A half-open probe checks the dependency before normal traffic resumes.",
    doc(
      "prescriptive-guidance/latest/cloud-design-patterns/circuit-breaker.html",
    ),
    "Dependency unavailable",
    "One call per second; consecutive-failure threshold; one half-open probe; baseline outage from t=4 through t=10.",
  ),
  lesson(
    "retries",
    "workflow",
    [
      k("attempts", "Attempt budget", 1, 5, 4),
      k("backoff", "Initial backoff", 1, 4, 1, "s"),
    ],
    { attempts: 1 },
    "No retry budget",
    "A transient failure may succeed later, but retries add load.",
    "Knock again after waiting longer, instead of hammering the door.",
    "Only retry safe operations; a timeout may hide a completed effect.",
    "for attempt in budget:\n  try: return idempotent_call()\n  catch transient: wait(exponential_backoff + seeded_jitter)\nreport_exhausted()",
    ["idempotency"],
    "What limits retry amplification here?",
    ["A finite attempt budget", "An infinite queue"],
    0,
    "The model stops after the configured budget, even if the dependency remains down.",
    doc(
      "prescriptive-guidance/latest/cloud-design-patterns/retry-backoff.html",
    ),
    "Dependency unavailable",
  ),
  lesson(
    "timeouts",
    "workflow",
    [
      k("deadline", "Caller deadline", 1, 8, 3, "s"),
      k("duration", "Remote operation duration", 1, 10, 5, "s"),
    ],
    { deadline: 7 },
    "Longer caller budget",
    "The user cannot wait forever for a remote operation.",
    "Stop waiting at the counter while the kitchen may still cook the order.",
    "A caller timeout does not prove the remote effect was cancelled.",
    "result = await_until(deadline, operation_id)\nif timed_out: report_unknown_outcome()\nreconcile(operation_id) before retrying()",
    ["idempotency"],
    "Can the remote effect finish after the caller times out?",
    ["No", "Yes"],
    1,
    "The operation and the caller’s waiting state are distinct.",
    "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
    "Remote dependency stalls",
  ),
  lesson(
    "bulkheads",
    "fleet",
    [rate(), k("reserved", "Critical pool capacity", 1, 5, 2, "req/s")],
    { rate: 10, reserved: 3 },
    "Noisy neighbor spike",
    "Background load must not consume checkout’s entire budget.",
    "Watertight ship compartments contain damage.",
    "Unused reserved capacity cannot always be borrowed by another pool.",
    "critical = dedicated_pool(reserved)\nbackground = dedicated_pool(total - reserved)\nreject_within_exhausted_pool_only()",
    ["rate-limiting"],
    "Can the noisy pool consume reserved critical slots?",
    ["No", "Yes"],
    0,
    "The reservation bounds each pool independently, even when one is idle.",
    doc("lambda/latest/dg/configuration-concurrency.html"),
    "Background pool fails",
  ),
  lesson(
    "health-checks",
    "fleet",
    [rate(), replicas(), k("checks", "Consecutive probes", 1, 4, 2)],
    { checks: 4 },
    "Slower health detection",
    "A process may accept connections while it cannot serve real work.",
    "Test the tap before directing thirsty visitors to it.",
    "Removing every unhealthy target can also remove all serving capacity.",
    "if failed_probes >= threshold: remove_target()\nif successful_probes >= threshold: restore_target()\nroute_only_to_ready_targets()",
    ["load-balancing"],
    "Does a recovered process immediately receive traffic in this model?",
    ["Yes", "No"],
    1,
    "It must pass the configured number of readiness probes first.",
    doc(
      "elasticloadbalancing/latest/application/target-group-health-checks.html",
    ),
    "First instance fails",
  ),
  lesson(
    "multi-az",
    "fleet",
    [rate(), replicas(), k("delay", "Failover delay", 1, 6, 2, "s")],
    { replicas: 1, delay: 5 },
    "No redundant instance",
    "One availability zone must be able to fail without losing every serving copy.",
    "Keep a spare supply in a different building.",
    "Failover still interrupts traffic and may require reconnection.",
    "on_zone_failure:\n  promote_healthy_standby()\n  refresh_connections_after_failover()\n  rebuild_redundancy()",
    ["replication", "health-checks"],
    "With one modeled instance, does another zone have capacity after it fails?",
    ["No", "Yes"],
    0,
    "Redundancy must exist before the zone loss.",
    doc(
      "AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraHighAvailability.html",
    ),
    "Zone A unavailable",
  ),
  lesson(
    "disaster-recovery",
    "workflow",
    [
      k("backup", "Last backup age", 1, 10, 3, "min"),
      k("restore", "Restore duration", 1, 10, 5, "s"),
    ],
    { backup: 9, restore: 9 },
    "Old backup, slow restore",
    "The primary is lost; recovery needs a usable tested backup.",
    "A photocopy helps only if it is recent enough and can be found.",
    "Replication can copy corruption; it is not a historical backup.",
    "snapshot = latest_verified_backup()\nrestore(snapshot)\nvalidate_service()\nmeasure(data_loss_window, recovery_time)",
    ["replication"],
    "Which setting increases this example’s possible data-loss window?",
    ["Backup age", "Playback speed"],
    0,
    "RPO is determined by the last usable recovery point, not animation time.",
    doc(
      "whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html",
    ),
    "Primary lost",
  ),
  lesson(
    "observability",
    "workflow",
    [k("sample", "Trace sample rate", 0, 100, 50, "%")],
    { sample: 10 },
    "Sparse traces",
    "Aggregate errors need a trace that explains the slow component.",
    "A receipt connects the steps of one purchase.",
    "Unsampled requests still exist and should still contribute to metrics.",
    "id = correlation_id()\nrecord_metric_for_every_request()\nif seeded_sample(rate): record_spans(id)\nlog_failure_with_id()",
    ["load-balancing"],
    "Do unsampled requests disappear from the request metric?",
    ["Yes", "No"],
    1,
    "Metrics cover every request; only detailed traces are sampled.",
    doc("xray/latest/devguide/aws-xray.html"),
    "Database span fails",
  ),

  lesson(
    "authentication",
    "identity",
    [
      k("lifetime", "Token lifetime", 1, 12, 6, "s"),
      k("invalid", "Invalid signatures", 0, 100, 20, "%"),
    ],
    { lifetime: 2, invalid: 50 },
    "Expired or invalid tokens",
    "A resource needs a verified caller identity.",
    "Check that a passport is authentic and still valid.",
    "Decoding a token does not verify its signature or authorize an action.",
    "verify_signature_issuer_client_and_expiry(token)\nif invalid: return 401\nreturn verified_subject",
    [],
    "Does reading an unverified token payload establish identity?",
    ["No", "Yes"],
    0,
    "Only the modeled signature, issuer, client, and lifetime checks establish identity.",
    doc(
      "cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html",
    ),
  ),
  lesson(
    "authorization",
    "identity",
    [
      k("cross", "Cross-owner requests", 0, 100, 40, "%"),
      k("allow", "Allow own read: 0 no · 1 yes", 0, 1, 1),
    ],
    { cross: 80 },
    "Cross-user access",
    "Signed-in users must not access another user’s order.",
    "A valid employee badge does not open every locked room.",
    "Authentication alone never proves resource ownership.",
    'subject = authenticated_subject\nallow = action == "read" and resource.owner == subject\nif not allow: return 403',
    ["authentication"],
    "May a verified user read any owner’s order?",
    ["Yes", "No"],
    1,
    "The example requires both an allowed action and matching ownership.",
    doc("IAM/latest/UserGuide/reference_policies_evaluation-logic.html"),
  ),
  lesson(
    "encryption",
    "identity",
    [
      k("allow", "Decrypt permission: 0 deny · 1 allow", 0, 1, 1),
      k("rotation", "Rotate key at", 2, 12, 6, "s"),
    ],
    { allow: 0 },
    "KMS access denied",
    "Stored ciphertext must be unreadable without authorized key use.",
    "A sealed safe needs the correct key and permission to use it.",
    "Encryption is not a replacement for identity and authorization.",
    "data_key = kms.generate_data_key()\nstore(encrypt(object, data_key), wrapped_key)\non_read: authorize(); kms.decrypt(wrapped_key)",
    ["authorization"],
    "Does possessing ciphertext alone grant plaintext access?",
    ["No", "Yes"],
    0,
    "The modeled read also needs key permission. Rotation keeps older key material usable.",
    doc("kms/latest/developerguide/concepts.html"),
  ),
  lesson(
    "secrets",
    "identity",
    [
      k("refresh", "Credential refresh interval", 1, 12, 3, "s"),
      k("overlap", "Old credential overlap", 0, 8, 3, "s"),
    ],
    { refresh: 12, overlap: 0 },
    "Stale credential",
    "A rotated database credential must reach cached application clients.",
    "Replace a door code while allowing a short transition period.",
    "Changing the secret store does not instantly refresh every client.",
    "if cache_age >= refresh_interval: fetch_current_secret()\nrotate_and_validate(new_secret)\nretire_old_after_overlap()",
    ["authentication"],
    "Why can a healthy client fail after rotation?",
    ["Its cached credential is retired", "Rotation deletes the database"],
    0,
    "Refresh must complete before the old credential’s overlap window closes.",
    doc("secretsmanager/latest/userguide/rotating-secrets.html"),
  ),
  lesson(
    "network-isolation",
    "network",
    [
      k("public", "Public database rule: 0 closed · 1 open", 0, 1, 0),
      k("app", "Application ingress: 0 deny · 1 allow", 0, 1, 1),
    ],
    { public: 1 },
    "Overbroad ingress rule",
    "Only the application should connect to the database.",
    "An inner door admits staff even when the street door is public.",
    "A private subnet alone does not express every security-group rule.",
    "database.ingress = application_security_group\ndeny_internet_source()\nallow_return_traffic_for_established_connections()",
    [],
    "Which rule unnecessarily broadens database access?",
    ["Allow the application group", "Allow public sources"],
    1,
    "This topology gives the database no legitimate public client.",
    doc("vpc/latest/userguide/vpc-security-groups.html"),
  ),
  lesson(
    "edge-protection",
    "network",
    [
      k("abuse", "Abusive requests", 0, 100, 40, "%"),
      k("enforce", "Rule: 0 count · 1 block", 0, 1, 1),
    ],
    { enforce: 0 },
    "Observe-only rule",
    "Malicious requests should not consume origin capacity.",
    "Screen parcels before they reach the warehouse.",
    "Count mode observes matches but does not block them.",
    "match = inspect_http_request()\nif match and rule.enforcing: block()\nelse: forward_to_origin()\nrecord_match()",
    [],
    "In count mode, does a matching request reach the origin?",
    ["Yes", "No"],
    0,
    "Count mode records a match without enforcing a block.",
    doc("waf/latest/developerguide/web-acl-rule-actions.html"),
  ),
  lesson(
    "blue-green",
    "fleet",
    [
      rate(),
      k("switch", "Switch to green at", 2, 15, 8, "s"),
      k("errors", "Green error rate", 0, 100, 0, "%"),
    ],
    { errors: 50 },
    "Bad green deployment",
    "Validate a complete candidate fleet before switching traffic.",
    "Prepare a new theater stage, then move the audience between shows.",
    "A fleet switch cannot reverse an incompatible database migration.",
    "deploy_green(); validate_readiness()\nswitch_all_traffic_to_green()\nif errors_exceed_alarm: switch_back_to_blue()",
    ["health-checks"],
    "What is required for fast rollback?",
    ["Keep blue ready", "Delete blue immediately"],
    0,
    "Both environments stay ready during this modeled rollout.",
    doc("codedeploy/latest/userguide/deployments-create.html"),
    "Green fails",
  ),
  lesson(
    "canary",
    "fleet",
    [
      rate(),
      k("weight", "Candidate traffic share", 0, 100, 20, "%"),
      k("errors", "Candidate error rate", 0, 100, 30, "%"),
    ],
    { weight: 70 },
    "Larger candidate share",
    "Expose a new version to a controlled portion of traffic.",
    "Offer a new recipe to a few tables before changing the whole menu.",
    "A small sample can hide defects; observed and expected error rates differ.",
    "target = seeded_weighted_choice(candidate_weight)\nrecord_errors_by_version(target)\nif alarm: set_candidate_weight(0)",
    ["load-balancing"],
    "With a healthy stable version, what raises expected overall errors?",
    [
      "A larger share sent to a faulty candidate",
      "More healthy stable traffic",
    ],
    0,
    "Expected overall errors are candidate share × candidate error probability; observed counts use the finite seeded workload.",
    doc("lambda/latest/dg/configuring-alias-routing.html"),
    "Candidate fails",
  ),

  lesson(
    "eventual-consistency",
    "replica",
    [lag()],
    { lag: 8 },
    "Long propagation delay",
    "Two regions can temporarily disagree about a recent update.",
    "News reaches distant noticeboards at different times.",
    "Eventual consistency promises convergence under stated assumptions, not instant agreement.",
    "commit_local(version)\nship_ordered_update(remote)\nremote.apply_if_newer(version)\nread_local_copy()",
    ["replication"],
    "After writes stop and delivery resumes, what should happen?",
    ["Copies converge", "Copies must stay different"],
    0,
    "The model delivers all pending versions in order after the partition heals.",
    doc("amazondynamodb/latest/developerguide/GlobalTables.html"),
    "Replication link disconnected",
  ),
  lesson(
    "strong-consistency",
    "replica",
    [lag(), k("strong", "Read: 0 eventual · 1 strong", 0, 1, 1)],
    { strong: 0, lag: 8 },
    "Eventual read path",
    "A reader needs the latest successfully committed regional value.",
    "Ask the official ledger keeper rather than a delayed photocopy.",
    "DynamoDB GSIs do not support strongly consistent reads.",
    "if require_latest: table.get(consistent_read=true)\nelse: read_replica()\ncharge_read_capacity_for_selected_mode()",
    ["replication"],
    "Which path guarantees the latest committed value in this model?",
    ["Regional strong read", "Lagging copy"],
    0,
    "The strong path reads the authoritative committed state; modeled items are at most 4 KB.",
    doc("amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html"),
    "Replication link disconnected",
  ),
  lesson(
    "cap",
    "replica",
    [
      lag(),
      k("available", "Partition policy: 0 reject · 1 serve local", 0, 1, 0),
    ],
    { available: 1 },
    "Serve during partition",
    "A partition prevents coordination between two copies.",
    "Two isolated offices must decide whether to keep serving old paperwork.",
    "CAP applies during a network partition, not as a universal choose-two slogan.",
    "if partitioned and require_quorum: reject()\nelse: serve_local_value()\non_heal: reconcile_and_replicate()",
    ["eventual-consistency"],
    "What does the quorum path sacrifice during this partition?",
    ["Availability for isolated reads", "All data durability"],
    0,
    "It rejects requests it cannot safely coordinate; the local path remains available but may be stale.",
    doc("whitepapers/latest/availability-and-beyond-improving-resilience/"),
    "Network partition",
    "Two copies; primary-only writes; no concurrent conflicting writers; baseline partition t=4..10.",
  ),
  lesson(
    "cqrs",
    "replica",
    [lag()],
    { lag: 9 },
    "Slow read projection",
    "Write validation and read queries need different shapes.",
    "The transaction journal and customer-facing statement serve different jobs.",
    "Separate models need not be separate microservices, and projections may lag.",
    "command.validate_and_commit()\nstream.onEvent(event): update_query_projection(event)\nquery: read_projection()",
    ["eventual-consistency"],
    "Can a successful command precede its appearance in the query view?",
    ["Yes", "No"],
    0,
    "The projection consumes the committed event asynchronously.",
    "https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs",
    "Projection consumer stopped",
  ),
  lesson(
    "event-sourcing",
    "workflow",
    [
      k("history", "Retained events", 4, 20, 10),
      k("snapshot", "Snapshot through event", 0, 10, 0),
    ],
    { snapshot: 6 },
    "Start from snapshot",
    "A current balance must be rebuildable from the record of changes.",
    "Reconstruct a score by replaying the scorebook.",
    "A materialized view is replaceable; the event history is the durable source.",
    "state = snapshot.state or initial_state\nfor event after snapshot.position:\n  state = fold(state, event)\ncheckpoint_projection()",
    ["cqrs"],
    "Does using a valid snapshot change the final folded value?",
    ["Yes", "No"],
    1,
    "It skips work already represented in the snapshot while preserving the same final state.",
    "https://learn.microsoft.com/en-us/azure/architecture/patterns/event-sourcing",
    "Projection worker stopped",
  ),
  lesson(
    "sagas",
    "workflow",
    [
      k("fail", "Fulfillment: 0 success · 1 failure", 0, 1, 0),
      k("compensation", "Compensation delay", 1, 6, 2, "s"),
    ],
    { fail: 1 },
    "Fulfillment failure",
    "A multi-service order cannot use one database transaction.",
    "Cancel each separate reservation in reverse order when the trip falls through.",
    "Compensation is a business action and can itself need retries.",
    "reserve_inventory()\nauthorize_payment()\ntry: fulfill()\ncatch: refund_payment(); release_inventory()",
    ["transactions", "idempotency"],
    "Does compensation erase the original payment event?",
    ["No, it adds a refund action", "Yes, history is deleted"],
    0,
    "Compensation changes business state through new events and may take time.",
    doc(
      "prescriptive-guidance/latest/cloud-design-patterns/saga-orchestration.html",
    ),
    "Fulfillment fails",
  ),
  lesson(
    "distributed-locks",
    "workflow",
    [
      k("pause", "First worker pause", 1, 12, 8, "s"),
      k("lease", "Lease duration", 2, 10, 5, "s"),
    ],
    { pause: 2 },
    "Worker resumes before expiry",
    "A paused lock holder may resume after its lease has expired.",
    "A later numbered ticket supersedes an earlier one.",
    "A lease alone does not stop stale side effects; the resource must enforce fencing.",
    "token = acquire_monotonic_fence()\nresource.write(value, token)\nresource.reject_if(token < highest_seen_fence)",
    ["optimistic-locking"],
    "Who must reject an old fencing token?",
    ["The protected resource", "Only the paused worker"],
    0,
    "The resource enforces ordering even if the old worker never notices it lost its lease.",
    doc(
      "amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html",
    ),
    "First worker pauses",
  ),
  lesson(
    "consistent-hashing",
    "hash",
    [
      k("nodes", "Initial nodes", 2, 6, 3),
      k("virtual", "Virtual positions per node", 1, 6, 3),
    ],
    { nodes: 5, virtual: 1 },
    "Sparse larger ring",
    "Adding a cache node should not remap nearly every key.",
    "Insert a new delivery district and move only its neighboring addresses.",
    "The ideal 1/(N+1) estimate is not an exact finite-ring outcome.",
    "positions = sort(hash(node, virtual_index))\nowner(key) = first_position_clockwise(hash(key))\nadd_node(); move_only_changed_owners()",
    ["sharding"],
    "With one new node, which keys move under ring ownership?",
    ["Only keys whose clockwise owner changes", "Every key"],
    0,
    "The renderer shows actual movement for 24 seeded keys and compares it with modulo hashing.",
    "https://www.cs.princeton.edu/courses/archive/fall09/cos518/papers/chash.pdf",
    "New node unavailable",
  ),
];
export function getLesson(id: string): Lesson {
  const found = lessons.find((l) => l.id === id);
  if (!found) throw new Error("Unknown lesson.");
  return found;
}
export const defaults = (id: string) =>
  Object.fromEntries(getLesson(id).controls.map((c) => [c.key, c.initial]));
export function recommendations(id: string): string[] {
  const dependents = lessons
    .filter((l) => l.prerequisites.includes(id))
    .map((l) => l.id);
  const concept = getConcept(id)!;
  return [
    ...new Set([
      ...dependents,
      ...concepts
        .filter((c) => c.group === concept.group && c.id !== id)
        .map((c) => c.id),
    ]),
  ].slice(0, 3);
}
